ALTER TABLE `ttl_rchave_historico`
ADD COLUMN `meta_1_date` DATE NULL DEFAULT NULL after descricao_1,
ADD COLUMN `meta_2_date` DATE NULL DEFAULT NULL after descricao_2,
ADD COLUMN `meta_3_date` DATE NULL DEFAULT NULL after descricao_3,
ADD COLUMN `meta_4_date` DATE NULL DEFAULT NULL after descricao_4,
ADD COLUMN `meta_5_date` DATE NULL DEFAULT NULL after descricao_5,
ADD COLUMN `meta_6_date` DATE NULL DEFAULT NULL after descricao_6,
ADD COLUMN `meta_7_date` DATE NULL DEFAULT NULL after descricao_7,
ADD COLUMN `meta_8_date` DATE NULL DEFAULT NULL after descricao_8,
ADD COLUMN `meta_9_date` DATE NULL DEFAULT NULL after descricao_9,
ADD COLUMN `meta_10_date` DATE NULL DEFAULT NULL after descricao_10,
ADD COLUMN `meta_11_date` DATE NULL DEFAULT NULL after descricao_11,
ADD COLUMN `meta_12_date` DATE NULL DEFAULT NULL after descricao_12,
ADD COLUMN `meta_13_date` DATE NULL DEFAULT NULL after descricao_13,
ADD COLUMN `meta_14_date` DATE NULL DEFAULT NULL after descricao_14,
ADD COLUMN `meta_15_date` DATE NULL DEFAULT NULL after descricao_15;